/**
 * @rotate/adapter-local-random — locally-generated cryptographic secrets.
 *
 * Rotates app-owned secrets that have no external provider: SESSION_SECRET,
 * JWT_SECRET, CRON_SECRET, HMAC_SECRET, AUTH_SECRET, webhook signing keys
 * generated by the app itself, etc.
 *
 * Each rotation generates a fresh value via Node's `crypto.randomBytes`.
 * Nothing is sent to the network — `verify` checks byte-length, `revoke`
 * is a no-op because the old value is only valid while consumers still
 * hold it (this adapter never stores the old value).
 *
 * ## Metadata
 *
 * - `bytes` (number, default 32) — entropy in raw bytes. 32 = 256 bits,
 *   matches industry defaults (Next.js session secret, NextAuth).
 * - `encoding` ("hex" | "base64url" | "base64", default "hex") — how the
 *   bytes are serialized into the Secret.value string. `base64url` is
 *   the safest default for env-var transport (URL-safe, no padding).
 * - `prefix` (string, optional) — prepended verbatim. Useful for
 *   disambiguating multiple random secrets in the same project
 *   (e.g. prefix: "whsec_" to mimic Stripe webhook-shape).
 */

import { randomBytes } from "node:crypto";
import { makeError } from "@rotate/core";
import type {
  Adapter,
  AuthContext,
  RotationResult,
  RotationSpec,
  Secret,
} from "@rotate/core/types";

const PROVIDER = "local-random";
const DEFAULT_BYTES = 32;
const MIN_BYTES = 16;
const MAX_BYTES = 128;
type Encoding = "hex" | "base64url" | "base64";

function parseBytes(raw: string | undefined): number {
  if (!raw) return DEFAULT_BYTES;
  const n = Number.parseInt(raw, 10);
  if (!Number.isFinite(n) || n < MIN_BYTES || n > MAX_BYTES) {
    throw new Error(
      `invalid metadata.bytes=${raw}; must be an integer in [${MIN_BYTES}, ${MAX_BYTES}]`,
    );
  }
  return n;
}

function parseEncoding(raw: string | undefined): Encoding {
  const enc = (raw ?? "hex") as Encoding;
  if (enc !== "hex" && enc !== "base64url" && enc !== "base64") {
    throw new Error(`invalid metadata.encoding=${raw}; must be hex | base64url | base64`);
  }
  return enc;
}

function generate(bytes: number, encoding: Encoding, prefix: string): string {
  const buf = randomBytes(bytes);
  return `${prefix}${buf.toString(encoding)}`;
}

export const localRandomAdapter: Adapter = {
  name: "local-random",

  async auth(): Promise<AuthContext> {
    // No remote credentials — return a placeholder env ctx so the orchestrator
    // treats this adapter uniformly alongside provider-backed ones.
    return { kind: "env", varName: "ROTATE_LOCAL_RANDOM", token: "local" };
  },

  async create(spec: RotationSpec, _ctx: AuthContext): Promise<RotationResult<Secret>> {
    try {
      const bytes = parseBytes(spec.metadata.bytes);
      const encoding = parseEncoding(spec.metadata.encoding);
      const prefix = spec.metadata.prefix ?? "";
      const value = generate(bytes, encoding, prefix);
      return {
        ok: true,
        data: {
          id: `local-${Date.now()}`,
          provider: PROVIDER,
          value,
          metadata: {
            bytes: String(bytes),
            encoding,
            prefix,
          },
          createdAt: new Date().toISOString(),
        },
      };
    } catch (cause) {
      return {
        ok: false,
        error: makeError("invalid_spec", String(cause), PROVIDER, { cause }),
      };
    }
  },

  async verify(secret: Secret, _ctx: AuthContext): Promise<RotationResult<boolean>> {
    const expectedBytes = parseBytes(secret.metadata.bytes);
    const encoding = parseEncoding(secret.metadata.encoding);
    const prefix = secret.metadata.prefix ?? "";
    if (!secret.value.startsWith(prefix)) {
      return { ok: true, data: false };
    }
    const encoded = secret.value.slice(prefix.length);
    // Decode + compare length rather than regex match — robust against
    // non-standard encodings or transport-whitespace.
    let decoded: Buffer;
    try {
      decoded = Buffer.from(encoded, encoding === "base64url" ? "base64url" : encoding);
    } catch {
      return { ok: true, data: false };
    }
    return { ok: true, data: decoded.length === expectedBytes };
  },

  async revoke(_secret: Secret, _ctx: AuthContext): Promise<RotationResult<void>> {
    // There is no provider to revoke against. The old value stops working
    // as soon as every consumer has been propagated and redeployed — the
    // orchestrator's grace-period logic already enforces that.
    return { ok: true, data: undefined };
  },
};

export default localRandomAdapter;
